name = "cf007"
main = "worker.js"
compatibility_date = "2024-05-02"

# Jika Anda membutuhkan variabel environment atau KV Namespace, 
# Anda bisa menambahkannya di bawah ini nanti.

# [vars]
# KEY = "VALUE"

# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
